// Generated from the IronCalc engine function table (all names verified against the engine).
// [name, category]
export const FUNCTION_TABLE: [string, string][] = [
  ["AND", "Logical"],
  ["FALSE", "Logical"],
  ["IF", "Logical"],
  ["IFERROR", "Logical"],
  ["IFNA", "Logical"],
  ["IFS", "Logical"],
  ["LAMBDA", "Logical"],
  ["LET", "Logical"],
  ["NOT", "Logical"],
  ["OR", "Logical"],
  ["SWITCH", "Logical"],
  ["TRUE", "Logical"],
  ["XOR", "Logical"],
  ["BYCOL", "Logical"],
  ["BYROW", "Logical"],
  ["MAP", "Logical"],
  ["REDUCE", "Logical"],
  ["SCAN", "Logical"],
  ["MAKEARRAY", "Logical"],
  ["ABS", "Math & Trig"],
  ["ACOS", "Math & Trig"],
  ["ACOSH", "Math & Trig"],
  ["ASIN", "Math & Trig"],
  ["ASINH", "Math & Trig"],
  ["ATAN", "Math & Trig"],
  ["ATAN2", "Math & Trig"],
  ["ATANH", "Math & Trig"],
  ["CHOOSE", "Math & Trig"],
  ["COLUMN", "Math & Trig"],
  ["COLUMNS", "Math & Trig"],
  ["COS", "Math & Trig"],
  ["COSH", "Math & Trig"],
  ["LOG", "Math & Trig"],
  ["LOG10", "Math & Trig"],
  ["LN", "Math & Trig"],
  ["MAX", "Math & Trig"],
  ["MIN", "Math & Trig"],
  ["PI", "Math & Trig"],
  ["POWER", "Math & Trig"],
  ["PRODUCT", "Math & Trig"],
  ["RAND", "Math & Trig"],
  ["RANDBETWEEN", "Math & Trig"],
  ["ROUND", "Math & Trig"],
  ["ROUNDDOWN", "Math & Trig"],
  ["ROUNDUP", "Math & Trig"],
  ["SIN", "Math & Trig"],
  ["SINH", "Math & Trig"],
  ["SQRT", "Math & Trig"],
  ["SQRTPI", "Math & Trig"],
  ["SUM", "Math & Trig"],
  ["SUMIF", "Math & Trig"],
  ["SUMIFS", "Math & Trig"],
  ["SUMX2MY2", "Math & Trig"],
  ["SUMX2PY2", "Math & Trig"],
  ["SUMXMY2", "Math & Trig"],
  ["TAN", "Math & Trig"],
  ["TANH", "Math & Trig"],
  ["ACOT", "Math & Trig"],
  ["ACOTH", "Math & Trig"],
  ["COT", "Math & Trig"],
  ["COTH", "Math & Trig"],
  ["CSC", "Math & Trig"],
  ["CSCH", "Math & Trig"],
  ["SEC", "Math & Trig"],
  ["SECH", "Math & Trig"],
  ["EXP", "Math & Trig"],
  ["FACT", "Math & Trig"],
  ["FACTDOUBLE", "Math & Trig"],
  ["SIGN", "Math & Trig"],
  ["RADIANS", "Math & Trig"],
  ["DEGREES", "Math & Trig"],
  ["INT", "Math & Trig"],
  ["EVEN", "Math & Trig"],
  ["ODD", "Math & Trig"],
  ["CEILING", "Math & Trig"],
  ["CEILING.MATH", "Math & Trig"],
  ["CEILING.PRECISE", "Math & Trig"],
  ["FLOOR", "Math & Trig"],
  ["FLOOR.MATH", "Math & Trig"],
  ["FLOOR.PRECISE", "Math & Trig"],
  ["ISO.CEILING", "Math & Trig"],
  ["MOD", "Math & Trig"],
  ["QUOTIENT", "Math & Trig"],
  ["MROUND", "Math & Trig"],
  ["TRUNC", "Math & Trig"],
  ["GCD", "Math & Trig"],
  ["LCM", "Math & Trig"],
  ["BASE", "Math & Trig"],
  ["DECIMAL", "Math & Trig"],
  ["ROMAN", "Math & Trig"],
  ["ARABIC", "Math & Trig"],
  ["COMBIN", "Math & Trig"],
  ["COMBINA", "Math & Trig"],
  ["SUMSQ", "Math & Trig"],
  ["MDETERM", "Math & Trig"],
  ["MINVERSE", "Math & Trig"],
  ["MUNIT", "Math & Trig"],
  ["MULTINOMIAL", "Math & Trig"],
  ["SERIESSUM", "Math & Trig"],
  ["SUMPRODUCT", "Math & Trig"],
  ["PERCENTOF", "Math & Trig"],
  ["ERROR.TYPE", "Information"],
  ["FORMULATEXT", "Information"],
  ["ISBLANK", "Information"],
  ["ISERR", "Information"],
  ["ISERROR", "Information"],
  ["ISEVEN", "Information"],
  ["ISFORMULA", "Information"],
  ["ISLOGICAL", "Information"],
  ["ISNA", "Information"],
  ["ISNONTEXT", "Information"],
  ["ISNUMBER", "Information"],
  ["ISODD", "Information"],
  ["ISOMITTED", "Information"],
  ["ISREF", "Information"],
  ["ISTEXT", "Information"],
  ["NA", "Information"],
  ["SHEET", "Information"],
  ["TYPE", "Information"],
  ["SHEETS", "Information"],
  ["N", "Information"],
  ["CELL", "Information"],
  ["INFO", "Information"],
  ["ADDRESS", "Lookup & Reference"],
  ["AREAS", "Lookup & Reference"],
  ["CHOOSECOLS", "Lookup & Reference"],
  ["CHOOSEROWS", "Lookup & Reference"],
  ["EXPAND", "Lookup & Reference"],
  ["FILTER", "Lookup & Reference"],
  ["HLOOKUP", "Lookup & Reference"],
  ["HSTACK", "Lookup & Reference"],
  ["INDEX", "Lookup & Reference"],
  ["INDIRECT", "Lookup & Reference"],
  ["LOOKUP", "Lookup & Reference"],
  ["MATCH", "Lookup & Reference"],
  ["OFFSET", "Lookup & Reference"],
  ["ROW", "Lookup & Reference"],
  ["ROWS", "Lookup & Reference"],
  ["SORT", "Lookup & Reference"],
  ["SORTBY", "Lookup & Reference"],
  ["UNIQUE", "Lookup & Reference"],
  ["VLOOKUP", "Lookup & Reference"],
  ["VSTACK", "Lookup & Reference"],
  ["WRAPCOLS", "Lookup & Reference"],
  ["WRAPROWS", "Lookup & Reference"],
  ["XLOOKUP", "Lookup & Reference"],
  ["XMATCH", "Lookup & Reference"],
  ["TRIMRANGE", "Lookup & Reference"],
  ["TAKE", "Lookup & Reference"],
  ["DROP", "Lookup & Reference"],
  ["TOCOL", "Lookup & Reference"],
  ["TOROW", "Lookup & Reference"],
  ["TRANSPOSE", "Lookup & Reference"],
  ["MMULT", "Lookup & Reference"],
  ["SEQUENCE", "Lookup & Reference"],
  ["RANDARRAY", "Lookup & Reference"],
  ["CONCAT", "Text"],
  ["TEXTSPLIT", "Text"],
  ["CONCATENATE", "Text"],
  ["EXACT", "Text"],
  ["FIND", "Text"],
  ["LEFT", "Text"],
  ["LEN", "Text"],
  ["LOWER", "Text"],
  ["MID", "Text"],
  ["REPT", "Text"],
  ["RIGHT", "Text"],
  ["SEARCH", "Text"],
  ["SUBSTITUTE", "Text"],
  ["REGEXEXTRACT", "Text"],
  ["REGEXREPLACE", "Text"],
  ["REGEXTEST", "Text"],
  ["T", "Text"],
  ["TEXT", "Text"],
  ["TEXTAFTER", "Text"],
  ["TEXTBEFORE", "Text"],
  ["TEXTJOIN", "Text"],
  ["TRIM", "Text"],
  ["UNICODE", "Text"],
  ["UNICHAR", "Text"],
  ["CHAR", "Text"],
  ["CLEAN", "Text"],
  ["CODE", "Text"],
  ["ASC", "Text"],
  ["ARRAYTOTEXT", "Text"],
  ["DOLLAR", "Text"],
  ["FINDB", "Text"],
  ["FIXED", "Text"],
  ["LEFTB", "Text"],
  ["LENB", "Text"],
  ["MIDB", "Text"],
  ["NUMBERVALUE", "Text"],
  ["PROPER", "Text"],
  ["REPLACE", "Text"],
  ["REPLACEB", "Text"],
  ["RIGHTB", "Text"],
  ["SEARCHB", "Text"],
  ["UPPER", "Text"],
  ["VALUE", "Text"],
  ["VALUETOTEXT", "Text"],
  ["AVERAGE", "Statistical"],
  ["AVERAGEA", "Statistical"],
  ["AVERAGEIF", "Statistical"],
  ["AVERAGEIFS", "Statistical"],
  ["COUNT", "Statistical"],
  ["COUNTA", "Statistical"],
  ["COUNTBLANK", "Statistical"],
  ["COUNTIF", "Statistical"],
  ["COUNTIFS", "Statistical"],
  ["MAXIFS", "Statistical"],
  ["MINIFS", "Statistical"],
  ["GEOMEAN", "Statistical"],
  ["AVEDEV", "Statistical"],
  ["BETA.DIST", "Statistical"],
  ["BETA.INV", "Statistical"],
  ["BINOM.DIST", "Statistical"],
  ["BINOM.DIST.RANGE", "Statistical"],
  ["BINOM.INV", "Statistical"],
  ["CHISQ.DIST", "Statistical"],
  ["CHISQ.DIST.RT", "Statistical"],
  ["CHISQ.INV", "Statistical"],
  ["CHISQ.INV.RT", "Statistical"],
  ["CHISQ.TEST", "Statistical"],
  ["CONFIDENCE.NORM", "Statistical"],
  ["CONFIDENCE.T", "Statistical"],
  ["COVARIANCE.P", "Statistical"],
  ["COVARIANCE.S", "Statistical"],
  ["DEVSQ", "Statistical"],
  ["EXPON.DIST", "Statistical"],
  ["F.DIST", "Statistical"],
  ["F.DIST.RT", "Statistical"],
  ["F.INV", "Statistical"],
  ["F.INV.RT", "Statistical"],
  ["F.TEST", "Statistical"],
  ["FISHER", "Statistical"],
  ["FISHERINV", "Statistical"],
  ["GAMMA", "Statistical"],
  ["GAMMA.DIST", "Statistical"],
  ["GAMMA.INV", "Statistical"],
  ["GAMMALN", "Statistical"],
  ["GAMMALN.PRECISE", "Statistical"],
  ["GAUSS", "Statistical"],
  ["HARMEAN", "Statistical"],
  ["HYPGEOM.DIST", "Statistical"],
  ["KURT", "Statistical"],
  ["LARGE", "Statistical"],
  ["LOGNORM.DIST", "Statistical"],
  ["LOGNORM.INV", "Statistical"],
  ["MAXA", "Statistical"],
  ["MEDIAN", "Statistical"],
  ["MINA", "Statistical"],
  ["NEGBINOM.DIST", "Statistical"],
  ["NORM.DIST", "Statistical"],
  ["NORM.INV", "Statistical"],
  ["NORM.S.DIST", "Statistical"],
  ["NORM.S.INV", "Statistical"],
  ["PEARSON", "Statistical"],
  ["PHI", "Statistical"],
  ["POISSON.DIST", "Statistical"],
  ["RANK.AVG", "Statistical"],
  ["RANK.EQ", "Statistical"],
  ["SKEW", "Statistical"],
  ["SKEW.P", "Statistical"],
  ["SMALL", "Statistical"],
  ["STANDARDIZE", "Statistical"],
  ["STDEV", "Statistical"],
  ["STDEV.P", "Statistical"],
  ["STDEV.S", "Statistical"],
  ["STDEVA", "Statistical"],
  ["STDEVPA", "Statistical"],
  ["T.DIST", "Statistical"],
  ["T.DIST.2T", "Statistical"],
  ["T.DIST.RT", "Statistical"],
  ["T.INV", "Statistical"],
  ["T.INV.2T", "Statistical"],
  ["T.TEST", "Statistical"],
  ["VAR.P", "Statistical"],
  ["VAR.S", "Statistical"],
  ["VARPA", "Statistical"],
  ["VARA", "Statistical"],
  ["WEIBULL.DIST", "Statistical"],
  ["Z.TEST", "Statistical"],
  ["BETADIST", "Compatibility"],
  ["HYPGEOMDIST", "Compatibility"],
  ["LOGNORMDIST", "Compatibility"],
  ["NEGBINOMDIST", "Compatibility"],
  ["NORMSDIST", "Compatibility"],
  ["TDIST", "Compatibility"],
  ["CHIDIST", "Compatibility"],
  ["CHIINV", "Compatibility"],
  ["CHITEST", "Compatibility"],
  ["CONFIDENCE", "Compatibility"],
  ["COVAR", "Compatibility"],
  ["CRITBINOM", "Compatibility"],
  ["LOGINV", "Compatibility"],
  ["BETAINV", "Compatibility"],
  ["BINOMDIST", "Compatibility"],
  ["EXPONDIST", "Compatibility"],
  ["FDIST", "Compatibility"],
  ["FINV", "Compatibility"],
  ["FTEST", "Compatibility"],
  ["GAMMADIST", "Compatibility"],
  ["GAMMAINV", "Compatibility"],
  ["MODE", "Compatibility"],
  ["NORMDIST", "Compatibility"],
  ["NORMINV", "Compatibility"],
  ["NORMSINV", "Compatibility"],
  ["PERCENTILE", "Compatibility"],
  ["PERCENTRANK", "Compatibility"],
  ["POISSON", "Compatibility"],
  ["QUARTILE", "Compatibility"],
  ["RANK", "Compatibility"],
  ["STDEVP", "Compatibility"],
  ["TINV", "Compatibility"],
  ["TTEST", "Compatibility"],
  ["VAR", "Compatibility"],
  ["VARP", "Compatibility"],
  ["WEIBULL", "Compatibility"],
  ["ZTEST", "Compatibility"],
  ["DATE", "Date & Time"],
  ["DATEDIF", "Date & Time"],
  ["DATEVALUE", "Date & Time"],
  ["DAY", "Date & Time"],
  ["EDATE", "Date & Time"],
  ["EOMONTH", "Date & Time"],
  ["MONTH", "Date & Time"],
  ["TIME", "Date & Time"],
  ["TIMEVALUE", "Date & Time"],
  ["HOUR", "Date & Time"],
  ["MINUTE", "Date & Time"],
  ["SECOND", "Date & Time"],
  ["NOW", "Date & Time"],
  ["TODAY", "Date & Time"],
  ["YEAR", "Date & Time"],
  ["NETWORKDAYS", "Date & Time"],
  ["NETWORKDAYS.INTL", "Date & Time"],
  ["DAYS", "Date & Time"],
  ["DAYS360", "Date & Time"],
  ["WEEKDAY", "Date & Time"],
  ["WEEKNUM", "Date & Time"],
  ["WORKDAY", "Date & Time"],
  ["WORKDAY.INTL", "Date & Time"],
  ["YEARFRAC", "Date & Time"],
  ["ISOWEEKNUM", "Date & Time"],
  ["ACCRINT", "Financial"],
  ["ACCRINTM", "Financial"],
  ["DISC", "Financial"],
  ["FVSCHEDULE", "Financial"],
  ["INTRATE", "Financial"],
  ["PRICEDISC", "Financial"],
  ["PRICEMAT", "Financial"],
  ["RECEIVED", "Financial"],
  ["YIELDDISC", "Financial"],
  ["YIELDMAT", "Financial"],
  ["CUMIPMT", "Financial"],
  ["CUMPRINC", "Financial"],
  ["DB", "Financial"],
  ["DDB", "Financial"],
  ["DOLLARDE", "Financial"],
  ["DOLLARFR", "Financial"],
  ["EFFECT", "Financial"],
  ["FV", "Financial"],
  ["IPMT", "Financial"],
  ["IRR", "Financial"],
  ["ISPMT", "Financial"],
  ["MIRR", "Financial"],
  ["NOMINAL", "Financial"],
  ["NPER", "Financial"],
  ["NPV", "Financial"],
  ["PDURATION", "Financial"],
  ["PMT", "Financial"],
  ["PPMT", "Financial"],
  ["PV", "Financial"],
  ["RATE", "Financial"],
  ["RRI", "Financial"],
  ["SLN", "Financial"],
  ["SYD", "Financial"],
  ["TBILLEQ", "Financial"],
  ["TBILLPRICE", "Financial"],
  ["TBILLYIELD", "Financial"],
  ["XIRR", "Financial"],
  ["XNPV", "Financial"],
  ["DURATION", "Financial"],
  ["MDURATION", "Financial"],
  ["PRICE", "Financial"],
  ["YIELD", "Financial"],
  ["ODDFPRICE", "Financial"],
  ["ODDFYIELD", "Financial"],
  ["ODDLPRICE", "Financial"],
  ["ODDLYIELD", "Financial"],
  ["COUPDAYBS", "Financial"],
  ["COUPDAYS", "Financial"],
  ["COUPDAYSNC", "Financial"],
  ["COUPNCD", "Financial"],
  ["COUPNUM", "Financial"],
  ["COUPPCD", "Financial"],
  ["AMORDEGRC", "Financial"],
  ["AMORLINC", "Financial"],
  ["VDB", "Financial"],
  ["BESSELI", "Engineering"],
  ["BESSELJ", "Engineering"],
  ["BESSELK", "Engineering"],
  ["BESSELY", "Engineering"],
  ["ERF", "Engineering"],
  ["ERFC", "Engineering"],
  ["ERFC.PRECISE", "Engineering"],
  ["ERF.PRECISE", "Engineering"],
  ["BIN2DEC", "Engineering"],
  ["BIN2HEX", "Engineering"],
  ["BIN2OCT", "Engineering"],
  ["DEC2BIN", "Engineering"],
  ["DEC2HEX", "Engineering"],
  ["DEC2OCT", "Engineering"],
  ["HEX2BIN", "Engineering"],
  ["HEX2DEC", "Engineering"],
  ["HEX2OCT", "Engineering"],
  ["OCT2BIN", "Engineering"],
  ["OCT2DEC", "Engineering"],
  ["OCT2HEX", "Engineering"],
  ["BITAND", "Engineering"],
  ["BITLSHIFT", "Engineering"],
  ["BITOR", "Engineering"],
  ["BITRSHIFT", "Engineering"],
  ["BITXOR", "Engineering"],
  ["COMPLEX", "Engineering"],
  ["IMABS", "Engineering"],
  ["IMAGINARY", "Engineering"],
  ["IMARGUMENT", "Engineering"],
  ["IMCONJUGATE", "Engineering"],
  ["IMCOS", "Engineering"],
  ["IMCOSH", "Engineering"],
  ["IMCOT", "Engineering"],
  ["IMCSC", "Engineering"],
  ["IMCSCH", "Engineering"],
  ["IMDIV", "Engineering"],
  ["IMEXP", "Engineering"],
  ["IMLN", "Engineering"],
  ["IMLOG10", "Engineering"],
  ["IMLOG2", "Engineering"],
  ["IMPOWER", "Engineering"],
  ["IMPRODUCT", "Engineering"],
  ["IMREAL", "Engineering"],
  ["IMSEC", "Engineering"],
  ["IMSECH", "Engineering"],
  ["IMSIN", "Engineering"],
  ["IMSINH", "Engineering"],
  ["IMSQRT", "Engineering"],
  ["IMSUB", "Engineering"],
  ["IMSUM", "Engineering"],
  ["IMTAN", "Engineering"],
  ["CONVERT", "Engineering"],
  ["DELTA", "Engineering"],
  ["GESTEP", "Engineering"],
  ["SUBTOTAL", "Engineering"],
  ["DAVERAGE", "Database"],
  ["DCOUNT", "Database"],
  ["DGET", "Database"],
  ["DMAX", "Database"],
  ["DMIN", "Database"],
  ["DSUM", "Database"],
  ["DCOUNTA", "Database"],
  ["DPRODUCT", "Database"],
  ["DSTDEV", "Database"],
  ["DVAR", "Database"],
  ["DVARP", "Database"],
  ["DSTDEVP", "Database"],
  ["CORREL", "Statistical"],
  ["RSQ", "Statistical"],
  ["INTERCEPT", "Statistical"],
  ["SLOPE", "Statistical"],
  ["STEYX", "Statistical"],
  ["FORECAST", "Statistical"],
  ["FORECAST.LINEAR", "Statistical"],
  ["FORECAST.ETS", "Statistical"],
  ["FORECAST.ETS.CONFINT", "Statistical"],
  ["FORECAST.ETS.SEASONALITY", "Statistical"],
  ["FORECAST.ETS.STAT", "Statistical"],
  ["FREQUENCY", "Statistical"],
  ["GROWTH", "Statistical"],
  ["LINEST", "Statistical"],
  ["LOGEST", "Statistical"],
  ["MODE.MULT", "Statistical"],
  ["MODE.SNGL", "Statistical"],
  ["PERCENTILE.EXC", "Statistical"],
  ["PERCENTILE.INC", "Statistical"],
  ["PERCENTRANK.EXC", "Statistical"],
  ["PERCENTRANK.INC", "Statistical"],
  ["PERMUT", "Statistical"],
  ["PERMUTATIONA", "Statistical"],
  ["PROB", "Statistical"],
  ["QUARTILE.EXC", "Statistical"],
  ["QUARTILE.INC", "Statistical"],
  ["TREND", "Statistical"],
  ["TRIMMEAN", "Statistical"],
];
